objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Appointment No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Days_of_the_week__c</fullName>
        <label>Days of the week</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mon</fullName>
                </value>
                <value>
                    <fullName>Tue</fullName>
                </value>
                <value>
                    <fullName>Wed</fullName>
                </value>
                <value>
                    <fullName>Thur</fullName>
                </value>
                <value>
                    <fullName>Fri</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Major</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Computer Science</fullName>
                </value>
                <value>
                    <fullName>MIS</fullName>
                </value>
                <value>
                    <fullName>Software Engineering</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Timings__c</fullName>
        <label>Timings</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <label>Venue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CRS-{00000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Major</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Teacher__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teachers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TeacherDashboardController.cls
/*****************************************************************************************
	Class Name: TeacherDashboardController
	Purpose:Controller for the Teacher Dashboard Page
	******************************************************************************************/
public class TeacherDashboardController {    
    public Teacher__c tchr {get;set;}
    public Id userId{get;set;}
    public list<Course__c> courseList{get;set;}
    public Id crsId{get;set;}
    public List<Appointment__c>appList{get;set;}
    public Id appId{get;set;}
    public Appointment__c appTemp{get;set;}
	
	/*****************************************************************************************
	Method Name: TeacherDashboardController
	Purpose:Constructor method
	******************************************************************************************/
    public TeacherDashboardController(){
          UserId = UserInfo.getUserId();
          tchr = [SELECT ID,Name,Phone__c,Email__c,User__c from Teacher__c where User__c=:UserId];
          courseList = [SELECT ID,Name,Major__c,Course_Name__c,Days_of_the_week__c,Semester__c,Teacher__c,Timings__c,Venue__c FROM Course__c where Teacher__c=:tchr.id];
         Date tdy = Date.Today();
         appList = [SELECT ID,Name,Date__c,End_Time__c,Start_Time__c,Student__c,Teacher__c,teacher__r.name,Student__r.first_name__c,student__r.last_name__c,student__r.phone__c from Appointment__c where Teacher__c=:tchr.id and Date__c >:tdy];
    }
	
	/*****************************************************************************************
	Method Name: viewCourseDetails
	Purpose: Method to view details of selected course
	******************************************************************************************/
    public pageReference viewCourseDetails(){
         PageReference pf = new PageReference('/apex/CourseDetailsTeacherView?att='+crsId);
        return pf;
    }
	
	/*****************************************************************************************
	Method Name: cancelAppointment
	Purpose: Method to cancel an appointment
	******************************************************************************************/
    public void cancelAppointment(){
        list<Appointment__c> newAppList = new list<Appointment__c>();
    Appointment__c appToBeDeleted = null;
    for(Appointment__c app: appList){
        if(app.Id == appId) {
            appToBeDeleted = app;
             
        }
        else{
            newAppList.add(app);
        }
    }
    system.debug('appToBeDeleted...'+appToBeDeleted);
        if(appToBeDeleted != null){
               appTemp =new Appointment__c();
    appTemp = appToBeDeleted;
  
            database.delete(appToBeDeleted);
        }
    appList = newAppList;
    }
	
	/*****************************************************************************************
	Method Name: sendSMS
	Purpose: Method to send an SMS after the appointment is cancelled
	******************************************************************************************/
    public void sendSMS(){
      String account = Label.Twilio_Account_ID;
        String token = Label.Twilio_Token;    
        TwilioRestClient client = new TwilioRestClient(account, token);
        
        Map<String,String> params = new Map<String,String> {
                'To'   => appTemp.student__r.phone__c,
                'From' => '+12566079818',
                'Body' => 'Hi,'+appTemp.student__r.First_Name__c+' your appointment with Professor '+appTemp.teacher__r.name+ ' on '+appTemp.Date__c+' at '+appTemp.Start_Time__c+' has been cancelled. '
            };
        TwilioSMS sms = client.getAccount().getSMSMessages().create(params);
}
}