objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Appointment No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Points__c</fullName>
        <label>Total Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Major</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Computer Science</fullName>
                </value>
                <value>
                    <fullName>MIS</fullName>
                </value>
                <value>
                    <fullName>Software Engineering</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CRS-{00000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Assignments</relationshipLabel>
        <relationshipName>Course_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Course Assignments</relationshipLabel>
        <relationshipName>Course_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Course Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GRE_Score__c</fullName>
        <label>GRE Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Major__c</fullName>
        <label>Major</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Teacher__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_availability_Days__c</fullName>
        <label>Appointment availability Days</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mon</fullName>
                </value>
                <value>
                    <fullName>Tue</fullName>
                </value>
                <value>
                    <fullName>Wed</fullName>
                </value>
                <value>
                    <fullName>Thu</fullName>
                </value>
                <value>
                    <fullName>Fri</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teachers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DataFactory.cls
/*****************************************************************************************
	Class Name: DataFactory
	Purpose: Class to create data for testing
	******************************************************************************************/
public class DataFactory {
	
	/*****************************************************************************************
	Method Name: createUser
	Purpose: Method to create user record
	******************************************************************************************/
    public static User createUser(String profileName){
        Integer randomNumber = Integer.valueof((Math.random() * 100));
         Profile p = [SELECT Id FROM Profile WHERE Name=:profileName];
         User u = new User(Alias = 'standt', Email='testtrrrr'+randomNumber+'@gmail.com', 
            EmailEncodingKey='UTF-8', LastName='student', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testrrrr'+randomNumber+'@gmail.com');
            insert u;
        return u;
    }
	
	/*****************************************************************************************
	Method Name: createStudent
	Purpose: Method to create student record
	******************************************************************************************/
    public static Student__c createStudent(Id uId){
        Student__c st = new Student__c();
        st.First_Name__c = 'testFirstName';
        st.Last_Name__c = 'testLastName';
        st.Phone__c = '9999999';
        st.Email__c = 'test@test.com';
        st.Address__c = 'test address';
        st.GRE_Score__c = 311;
        st.Major__c = 'Computer Science';
        st.User__c=uId;
        //Set to 1 in the beginning when application is converted to student
        st.semester__c = '1';
        insert st;
        return st;
    }
	
	/*****************************************************************************************
	Method Name: createTeacher
	Purpose: Method to create teacher record
	******************************************************************************************/
    public static Teacher__c createTeacher(){
        Teacher__c tch = new teacher__c();
        tch.name = 'test teacher';
        tch.Email__c ='test@test.com';
        tch.Phone__c = '9999999999';
        tch.Appointment_availability_Days__c='Mon;Tue';
        insert tch;
        return tch;
    }
	
	/*****************************************************************************************
	Method Name: createCourse
	Purpose: Method to create course record
	******************************************************************************************/
    public static Course__c createCourse(Teacher__c tch){
        Course__c cr = new Course__c();
        cr.Course_Name__c = 'test course';
        cr.Teacher__c = tch.Id;
        insert cr;
        return cr;
        
    }
	
	/*****************************************************************************************
	Method Name: createCourseAssignment
	Purpose: Method to create course assignment record
	******************************************************************************************/
    public static Course_Assignment__c  createCourseAssignment(Course__c crs,Student__c st){
        Course_Assignment__c ca =  new Course_Assignment__c();
        ca.Course__c = crs.id;
        ca.Student__c = st.id;
        insert ca;
        return ca;
    }
	
	/*****************************************************************************************
	Method Name: createInvoice
	Purpose: Method to create course invoice record
	******************************************************************************************/
    public static Invoice__c createInvoice(Student__c stud){
        Invoice__c inv = new Invoice__c();
        inv.Amount__c =4000;
        inv.Student__c = stud.Id;
        inv.Transaction_ID__c = 'test';
        insert inv;
        return inv;
    }
	
	/*****************************************************************************************
	Method Name: createApplication
	Purpose: Method to create course application record
	******************************************************************************************/
    public static Lead createApplication(){
        Lead ld = new lead();
        ld.FirstName = 'testFirstName';
        ld.lastName = 'testLastName';
        ld.Email='test@test.com';
        ld.Phone='99999';
        ld.Street='testStreet';
        ld.City='testCity';
        ld.State='testState';
        ld.Country='testCountry';
        ld.Major__c='Computer Science';
        ld.GRE_Score__c = 311;
        ld.Company='test';
        insert ld;
        return ld;
    }
	
	/*****************************************************************************************
	Method Name: createAppointment
	Purpose: Method to create course appointment record
	******************************************************************************************/
    public static Appointment__c createAppointment(Student__c stud,Teacher__c tch){
        Appointment__c app = new Appointment__c();
        app.student__c = stud.id;
        app.Teacher__c=tch.id;
        app.Date__c=date.today()+1;
        app.Start_Time__c=Time.newInstance(15, 15, 0, 0);
        app.End_Time__c=Time.newInstance(15, 30, 0, 0);
        insert app;
        return app;
    }
	
	/*****************************************************************************************
	Method Name: createAssignment
	Purpose: Method to create course assignment record
	******************************************************************************************/
    public static Assignment__c createAssignment(Course__C crs){
        Assignment__c assn = new Assignment__c();
        assn.Course__c = crs.Id;
        assn.Due_Date__c=date.today()+25;
        assn.Name = 'Assignment 1';
        assn.Questions__c ='What is JAVA?';
        assn.Total_Points__c =30;
        insert assn;
        return assn;
    }
	/*****************************************************************************************
	Method Name: createSubmission
	Purpose: Method to create course submission record
	******************************************************************************************/
    public static Submission__c createSubmission(Assignment__c assn,Student__C stud){
        Submission__c sub = new submission__c();
        sub.Assignment__c=assn.Id;
        sub.Student__c = stud.Id;
        insert sub;
        return sub;
    }
}