objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Appointment No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Students</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Teacher__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Teachers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TeacherDashboardController_Test.cls
/*****************************************************************************************
	Class Name: TeacherDashboardController_Test
	Purpose:Test class for TeacherDashboardController
	******************************************************************************************/
@isTest
public class TeacherDashboardController_Test {
     public static User u{get;set;}
    public static Teacher__c tc{get;set;}
    public static Appointment__c app{get;set;}
    public static Student__c stud{get;set;}
	
	/*****************************************************************************************
	Method Name: createData
	Purpose:Method to create test data
	******************************************************************************************/
	static void createData(){
        u =   DataFactory.createUser('Teacher Profile');
        tc = DataFactory.createTeacher();
        stud = DataFactory.createStudent(u.Id);
        app = DataFactory.createAppointment(stud,tc);
        tc.User__c =u.id;
        update tc;
    }
	
	/*****************************************************************************************
	Method Name: scenario1
	Purpose:Method to test the functionality
	******************************************************************************************/
     static testMethod void scenario1(){
         createData();
          System.runAs(u){
              TeacherDashboardController tch = new TeacherDashboardController();
              tch.viewCourseDetails();
              tch.appId = app.Id;
              
              tch.cancelAppointment();
              
          	
          }
     }
}