objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Appointment No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Teacher__c</fullName>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CRS-{00000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Course Assignments</relationshipLabel>
        <relationshipName>Course_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Course Assignments</relationshipLabel>
        <relationshipName>Course_Assignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course Assignment</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>Course Assignment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Teacher__c.object
<CustomObject>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StudentDashboardController_Test.cls
/*****************************************************************************************
	Class Name: StudentDashboardController_Test
	Purpose: Test class for StudentDashboardController
	******************************************************************************************/
@isTest(seeAllData=FALSE)
public class StudentDashboardController_Test {
    public static User u{get;set;}
    public static Student__c stud{get;set;}
    public static Teacher__c tch{get;set;}
    public static Course__c crs{get;set;}
    public static Course_Assignment__c ca{get;set;}
    public static Invoice__c inv{get;set;}
    public static Appointment__c app{get;set;}
    public static User admin{get;set;}
	
	/*****************************************************************************************
	Method Name: createData
	Purpose: Method to create test data
	******************************************************************************************/
    static void createData(){
        admin = DataFactory.createUser('System Administrator');
		u =   DataFactory.createUser('Student Profile');
        stud =  DataFactory.createStudent(u.Id); 
        tch = DataFactory.createTeacher();
        crs = DataFactory.createCourse(tch);
        ca = DataFactory.createCourseAssignment(crs,stud);
        inv =  DataFactory.createInvoice(stud);
        app = DataFactory.createAppointment(stud, tch);
    }
	
	/*****************************************************************************************
	Method Name: scenario1
	Purpose: Test method to test the functionality
	******************************************************************************************/
     static testMethod void scenario1(){
       createData();
         System.runAs(u){
     	StudentDashboardController st = new StudentDashboardController();
             test.startTest();

                 st.viewCourseDetails();
                 st.getCourses();
                 
                 st.getEnrolledCourses();
                 st.edit();
                 st.enroll();
                 st.closePopup();
                 st.saveCourses();
                 st.crsId = crs.Id;
                 st.removeCourse();
                 st.viewInvoice();
                
             	st.payFees();
               
                   //  st.appTemp= [SELECT ID,Name,Date__c,End_Time__c,Start_Time__c,Student__c,Teacher__c,Teacher__r.name,Teacher__r.Phone__c,Student__r.First_Name__c from Appointment__c where Id=:app.Id];

              //  st.sendSMS();
             test.stopTest();
         }
         
        
     }

}