objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Teacher__c</fullName>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CRS-{00000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Teacher__c.object
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/StudentAssignmentViewController_Test.cls
/*****************************************************************************************
	Class Name: StudentAssignmentViewController_Test
	Purpose: Test class for StudentAssignmentViewController
	******************************************************************************************/
@isTest
public class StudentAssignmentViewController_Test {
     public static User u{get;set;}
    public static Student__c stud{get;set;}
     public static Teacher__c tch{get;set;}
    public static Course__c crs{get;set;}
    public static Assignment__c asn{get;set;}
    public static Submission__c sub{get;set;}
	
	/*****************************************************************************************
	Method Name: createData
	Purpose: Method to create data for testing
	******************************************************************************************/
	 static void createData(){
         u =   DataFactory.createUser('Student Profile');
        stud =  DataFactory.createStudent(u.Id); 
          tch = DataFactory.createTeacher();
        crs = DataFactory.createCourse(tch);
         asn=DataFactory.createAssignment(crs);
         sub=DataFactory.createSubmission(asn, stud);
         
     }
	 
	 /*****************************************************************************************
	Method Name: scenario1
	Purpose: Test method to test functionality
	******************************************************************************************/
    static testMethod void scenario1(){
       createData();
        system.runAs(u){
            System.currentPageReference().getParameters().put('att', asn.Id);
            StudentAssignmentViewController sv =new StudentAssignmentViewController();
            sv.viewSubmission();
            
            Blob b = Blob.valueOf('Test Data');
    		sv.objattachment = new Attachment();
          //  sv.objattachment.ParentId = sub.id;
    	sv.objattachment.Name = 'Test Attachment for Parent';
    	sv.objattachment.Body = b;
            sv.saveAssignment();
            
        }
    }
}