objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Teacher__c</fullName>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CRS-{00000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Teacher__c.object
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CourseDetailsTeacherViewController_Test.cls
/*****************************************************************************************
	Class Name: CourseDetailsTeacherViewController_Test
	Purpose: Test class for CourseDetailsTeacherViewController
	******************************************************************************************/
@isTest
public class CourseDetailsTeacherViewController_Test {
    public static teacher__c tch{get;set;}
    public static course__c crs{get;set;}
    public static assignment__c asn{get;set;}
	
	/*****************************************************************************************
	Method Name: createData
	Purpose: Method to create data for testing
	******************************************************************************************/
	static void createData(){
         tch = DataFactory.createTeacher();
        crs = DataFactory.createCourse(tch);
        asn = DataFactory.createAssignment(crs);
        
    }
	
	/*****************************************************************************************
	Method Name: scenario1
	Purpose: Test method for testing functionality
	******************************************************************************************/
     static testMethod void scenario1(){
       createData();
         System.currentPageReference().getParameters().put('att', crs.Id);
         CourseDetailsTeacherViewController cr = new CourseDetailsTeacherViewController();
         cr.createAssignment();
         cr.viewSubmissions();
         cr.closePopup();
         cr.saveAssignment();
         cr.assmntId = asn.Id;
          cr.createAssignment();
         cr.newAssignment = asn;
          cr.saveAssignment();
         
     }
}