objects/Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Course__c</fullName>
        <label>Course</label>
        <referenceTo>Course__c</referenceTo>
        <relationshipLabel>Assignments</relationshipLabel>
        <relationshipName>Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Total_Points__c</fullName>
        <label>Total Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CRS-{00000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CourseDetailsTeacherViewController.cls
/*****************************************************************************************
	Class Name: CourseDetailsTeacherViewController
	Purpose: Controller for CourseDetailsTeacherView Page
	******************************************************************************************/
public class CourseDetailsTeacherViewController {
    public Id crsId{get;set;}
    public Date dat{get;set;}
    public Course__c crs{get;set;}
    public Boolean showPopup{get;set;}
    public String assmntId{get;set;}
    public list<Assignment__c> assgnmtList{get;set;}
    public Assignment__c newAssignment {get;set;}
    public CourseDetailsTeacherViewController(){
        crsId=apexpages.currentpage().getparameters().get('att');
        crs=[SELECT ID,Name,Course_Name__c from Course__c where id=:crsId];
        assgnmtList=[SELECT ID,Name,Course__c,Due_Date__c,Total_Points__c,Questions__c from Assignment__c where Course__c =:crsId];
    }
	
	/*****************************************************************************************
	Method Name: createAssignment
	Purpose: Method to create assignment
	******************************************************************************************/
    public void createAssignment(){
         showPopup=true;
         System.debug('assmntId...'+assmntId);
         if(assmntId == NULL || assmntId=='') {
              newAssignment = new Assignment__c();
         }
         else{
             newAssignment = [SELECT ID,Name,Questions__c,Due_Date__c,Total_Points__c from Assignment__c where ID=:assmntId];
             dat = newAssignment.due_date__c;
         }
       
       
    }
	
	/*****************************************************************************************
	Method Name: viewSubmissions
	Purpose: Method to view submissions for selected assignment
	******************************************************************************************/
    public pageReference viewSubmissions(){
         PageReference pf = new PageReference('/apex/AssignmentSubmission?att='+assmntId);
         return pf;
    }
	
	/*****************************************************************************************
	Method Name: closePopup
	Purpose: Method to close the create assignment popup
	******************************************************************************************/
    public void closePopup(){
        showpopup=false;
    }
	
	/*****************************************************************************************
	Method Name: saveAssignment
	Purpose: Method to save assignment record
	******************************************************************************************/
    public void saveAssignment(){
        if(newAssignment.Id == NULL) {
            if(newAssignment.Name != '' && newAssignment.Questions__c != '' && dat!=NULL && newAssignment.Total_Points__c != NULL) {
                newAssignment.course__c = crsId;
                newAssignment.Due_Date__c = dat;
                insert newAssignment;
                assgnmtList.add(newAssignment);
                showPopup = false;
            }
          
        }
        else{
            newAssignment.due_date__c = dat;
            update newAssignment;
            for(Assignment__c assn : assgnmtList){
                if(assn.Id == newAssignment.Id) {
                    assn.Name = newAssignment.name;
                    assn.Questions__c = newAssignment.Questions__c;
                    assn.due_date__c = newAssignment.due_date__c;
                    assn.Total_Points__c = newAssignment.Total_Points__c;
                  
                }
            }
            showPopup = false;
            assmntId = NULL;
            dat = NULL;
        }
    }
}