objects/Assignment__c.object
<CustomObject>
    <label>Assignment</label>
    <nameField>
        <label>Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Submission__c.object
<CustomObject>
    <fields>
        <fullName>Assignment__c</fullName>
        <label>Assignment</label>
        <referenceTo>Assignment__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{00000}</displayFormat>
        <label>Submission No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AssignmentSubmissionController.cls
/*****************************************************************************************
Class Name: AssignmentSubmissionController
Purpose: Controller for AssignmentSubmissionPage
******************************************************************************************/
public class AssignmentSubmissionController{
    public Id assnId{get;set;}
    public list<Submission__c> submissionList {get;set;}
    public set<Id> subIdSet{get;set;}
    public list<Attachment> docsList{get;set;}
    public Assignment__c assn{get;set;}
    public Id docId{get;set;}
	
	/*****************************************************************************************
	Method Name: AssignmentSubmissionController
	Purpose: Constructor method
	******************************************************************************************/	
    public AssignmentSubmissionController(){
        subIdSet = new set<Id>();
		//get the assignment from the URL Parameter
        assnId=apexpages.currentpage().getparameters().get('att');
        assn = [SELECT ID,Name from Assignment__c where ID=:assnId];
		//query submission for the assignment
        submissionList = [SELECT ID,Name,Assignment__c,Score__c,Student__c from Submission__c where Assignment__c =:assnId];
        if(!submissionList.isEmpty()){
            for(Submission__c sub: submissionList) {
                subIdSet.add(sub.Id);
            }
			//query the files attached to the submission record
            docsList = [SELECT ID,Name,ParentId from Attachment where ParentID IN:subIdSet];
        }
    }
	
	/*****************************************************************************************
	Method Name: viewSubmission
	Purpose: Method to redirect to the submission page
	******************************************************************************************/	
    public pageReference viewSubmission(){
        PageReference pf = new PageReference('/'+docId);
        
        return pf;
    }
}