objects/Course__c.object
<CustomObject>
    <fields>
        <fullName>Teacher__c</fullName>
        <label>Teacher</label>
        <referenceTo>Teacher__c</referenceTo>
        <relationshipLabel>Courses</relationshipLabel>
        <relationshipName>Courses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Course</label>
    <nameField>
        <displayFormat>CRS-{00000}</displayFormat>
        <label>Course ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Teacher__c.object
<CustomObject>
    <label>Teacher</label>
    <nameField>
        <label>Teacher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teachers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CourseDetailsController_Test.cls
/*****************************************************************************************
	Class Name: CourseDetailsController_Test
	Purpose: Test class for CourseDetailsController
	******************************************************************************************/
@isTest
public class CourseDetailsController_Test {
    public static teacher__c tch{get;set;}
    public static course__c crs{get;set;}
	
	/*****************************************************************************************
	Method Name: createData
	Purpose: Method to create data for testing
	******************************************************************************************/
	static void createData(){
        tch = DataFactory.createTeacher();
        crs = DataFactory.createCourse(tch);
    }
	
	/*****************************************************************************************
	Method Name: scenario1
	Purpose: Test Method to test the functionality
	******************************************************************************************/
     static testMethod void scenario1(){
       createData();
         System.currentPageReference().getParameters().put('att', crs.Id);
         CourseDetailsController cr = new CourseDetailsController();
		 cr.viewAssignmentDetails();
     }
}