objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Student__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000000000}</displayFormat>
        <label>Invoice#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FeePaymentController.cls
/*****************************************************************************************
	Class Name: FeePaymentController
	Purpose: Controller for fee payment page
	******************************************************************************************/
public class FeePaymentController{
    public String attr{get;set;}
    public Id studId{get;set;}
    public String Amount{get;set;}
    public  FeePaymentHelper p{get;set;}
    public String txnId{get;set;}
    public Student__c stud{get;set;}
	
	/*****************************************************************************************
	Method Name: FeePaymentController
	Purpose: Constructor method
	******************************************************************************************/
    public FeePaymentController(){
       
        txnId = null;
         attr = apexpages.currentpage().getparameters().get('att');
         list<String> tempList = new List<String>();
         tempList = attr.split(',');
        studId = tempList[0];
        Amount =tempList[1];
         stud = [SELECT ID, First_Name__c,Last_Name__c from Student__c where id=:studId];
        p = new FeePaymentHelper();
    }
	
	/*****************************************************************************************
	Method Name: MakePayment
	Purpose: Method that gets called when user clicks on Make Payment
	******************************************************************************************/
    public PageReference MakePayment()
    {
        PageReference pf = null;
        System.debug('firstName..'+p.FirstName);
        p.amount = amount;
        p.FirstName = stud.first_name__c;
        p.LastName = stud.last_name__c;
        string message = p.pay();
       txnId = p.transid;
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,message));
        if(txnId != NULL) {
            Invoice__c inv = new Invoice__c();
            inv.Student__c = studId;
            inv.amount__c = Decimal.valueOf(amount);
            inv.Transaction_ID__c = txnId;
            insert inv;
            pf = new PageReference('/'+inv.Id);
        }
        return pf;
    }
}