objects/SM_Answer__c.object
<CustomObject>
    <description>Survey Monkey Answer object for Survey Answer details from SurveryMonkey API</description>
    <fields>
        <fullName>Answer_Id__c</fullName>
        <externalId>true</externalId>
        <label>Answer Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SM_Question__c</fullName>
        <label>SM Question</label>
        <referenceTo>SM_Question__c</referenceTo>
        <relationshipLabel>SM Answers</relationshipLabel>
        <relationshipName>SM_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>SM Answer</label>
    <nameField>
        <label>SM Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SM Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SM_Question__c.object
<CustomObject>
    <description>SurveyMonkey Question custom object  for Survey Question details from SurveryMonkey API</description>
    <fields>
        <fullName>question_id__c</fullName>
        <externalId>true</externalId>
        <label>question id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SM Question</label>
    <nameField>
        <label>SM Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SM Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SurveyMonkeyResp__c.object
<CustomObject>
    <fields>
        <fullName>Choice_Id__c</fullName>
        <label>Choice Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SM_Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SM Answer</label>
        <referenceTo>SM_Answer__c</referenceTo>
        <relationshipLabel>SurveyMonkeyResps</relationshipLabel>
        <relationshipName>SurveyMonkeyResps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SM_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SM Question</label>
        <referenceTo>SM_Question__c</referenceTo>
        <relationshipLabel>SurveyMonkeyResps</relationshipLabel>
        <relationshipName>SurveyMonkeyResps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>question_Id__c</fullName>
        <label>question Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>SurveyMonkeyResp</label>
    <nameField>
        <label>SurveyMonkeyResp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SurveyMonkeyResps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SurveyMonkeyRespHandler.cls
/*****************************************************************************************
	Class Name: SurveyMonkeyRespHandler
	Purpose:Handler class for the SurveyMonkeyResponseTrigger
	******************************************************************************************/
public with sharing class SurveyMonkeyRespHandler {
	/*****************************************************************************************
	Method Name: beforeInsert
	Purpose: Before insert trigger method
	******************************************************************************************/
	public static void beforeInsert(List<SurveyMonkeyResp__c> newLst) {
        Set<Decimal> allQIds = new Set<Decimal>();
        Set<Decimal> allAIds = new Set<Decimal>();
        Map<Decimal, Id> QMap = new Map<Decimal, Id>();
        Map<Decimal, Id> AMap = new Map<Decimal, Id>();
        for (SurveyMonkeyResp__c smr : newLst) {
            allQIds.add(smr.question_Id__c);
            allAIds.add(smr.Choice_Id__c);
        }
        for (SM_Answer__c a :
            [select Id, Answer_Id__c from SM_Answer__c where Answer_Id__c in :allAIds]) {
            
            AMap.put(a.Answer_Id__c, a.Id);
        }
        for (SM_Question__c q : 
            [select Id, Question_Id__c from SM_Question__c where question_Id__c in :allQIds]) {

            QMap.put(q.Question_Id__c, q.Id);    
        }
        for (SurveyMonkeyResp__c smr : newLst) {
            smr.SM_Answer__c = AMap.get(smr.Choice_Id__c);
            smr.SM_Question__c = QMap.get(smr.question_Id__c);
        }
    } 
}